INSERT IGNORE INTO genres (name) VALUES ('Agama');
INSERT IGNORE INTO genres (name) VALUES ('Anak');
INSERT IGNORE INTO genres (name) VALUES ('Ensiklopedia');
INSERT IGNORE INTO genres (name) VALUES ('Fantasi');
INSERT IGNORE INTO genres (name) VALUES ('Fiksi Anak Remaja');
INSERT IGNORE INTO genres (name) VALUES ('Kamus');
INSERT IGNORE INTO genres (name) VALUES ('Keterampilan');
INSERT IGNORE INTO genres (name) VALUES ('Manga');
INSERT IGNORE INTO genres (name) VALUES ('Matematika');
INSERT IGNORE INTO genres (name) VALUES ('Olahraga');
INSERT IGNORE INTO genres (name) VALUES ('SD');