INSERT IGNORE INTO genres (name) VALUES ('agama');
INSERT IGNORE INTO genres (name) VALUES ('Arsitektur');
INSERT IGNORE INTO genres (name) VALUES ('Biografi');
INSERT IGNORE INTO genres (name) VALUES ('Bisnis Ekonomi');
INSERT IGNORE INTO genres (name) VALUES ('Buku Anak');
INSERT IGNORE INTO genres (name) VALUES ('Buku Masakan');
INSERT IGNORE INTO genres (name) VALUES ('Buku Pendukung Belajar');
INSERT IGNORE INTO genres (name) VALUES ('desain');
INSERT IGNORE INTO genres (name) VALUES ('fiksi-sastra');
INSERT IGNORE INTO genres (name) VALUES ('fiksi-teenlit');
INSERT IGNORE INTO genres (name) VALUES ('filsafat');
INSERT IGNORE INTO genres (name) VALUES ('fotografi');
INSERT IGNORE INTO genres (name) VALUES ('game-aktivitas');
INSERT IGNORE INTO genres (name) VALUES ('home-living');
INSERT IGNORE INTO genres (name) VALUES ('hukum');
INSERT IGNORE INTO genres (name) VALUES ('humaniora');
INSERT IGNORE INTO genres (name) VALUES ('humor');
INSERT IGNORE INTO genres (name) VALUES ('kamus');
INSERT IGNORE INTO genres (name) VALUES ('keluarga');
INSERT IGNORE INTO genres (name) VALUES ('kerajinan-hobi');
INSERT IGNORE INTO genres (name) VALUES ('komik');
INSERT IGNORE INTO genres (name) VALUES ('komputer-teknologi');
INSERT IGNORE INTO genres (name) VALUES ('lain-lain-2');
INSERT IGNORE INTO genres (name) VALUES ('matematika');
INSERT IGNORE INTO genres (name) VALUES ('medis');
INSERT IGNORE INTO genres (name) VALUES ('musik-1');
INSERT IGNORE INTO genres (name) VALUES ('nature');
INSERT IGNORE INTO genres (name) VALUES ('non-fiksi');
INSERT IGNORE INTO genres (name) VALUES ('nonfiksi-anak-remaja');
INSERT IGNORE INTO genres (name) VALUES ('novel');
INSERT IGNORE INTO genres (name) VALUES ('olahraga');
INSERT IGNORE INTO genres (name) VALUES ('pendidikan');
INSERT IGNORE INTO genres (name) VALUES ('pengembangan Diri');
INSERT IGNORE INTO genres (name) VALUES ('pengembangan Diri');
INSERT IGNORE INTO genres (name) VALUES ('Perawatan Hewan Peliharaan');
INSERT IGNORE INTO genres (name) VALUES ('Perkebunan');
INSERT IGNORE INTO genres (name) VALUES ('Politik Pemerintah');
INSERT IGNORE INTO genres (name) VALUES ('Puisi');
INSERT IGNORE INTO genres (name) VALUES ('Refrensi');
INSERT IGNORE INTO genres (name) VALUES ('Sains');
INSERT IGNORE INTO genres (name) VALUES ('Sastra');
INSERT IGNORE INTO genres (name) VALUES ('Seni Pertunjukan');
INSERT IGNORE INTO genres (name) VALUES ('Seni Rupa');
INSERT IGNORE INTO genres (name) VALUES ('Sosial');
INSERT IGNORE INTO genres (name) VALUES ('Teknik');
INSERT IGNORE INTO genres (name) VALUES ('Transportasi');
INSERT IGNORE INTO genres (name) VALUES ('Travel');
INSERT IGNORE INTO genres (name) VALUES ('Tubuh Pikiran Jiwa');
INSERT IGNORE INTO genres (name) VALUES ('Matematika');
INSERT IGNORE INTO genres (name) VALUES ('IPAS');
INSERT IGNORE INTO genres (name) VALUES ('Pendidikan Agama Kristen');
INSERT IGNORE INTO genres (name) VALUES ('Bahasa Indonesia');
INSERT IGNORE INTO genres (name) VALUES ('Bahasa Inggris');
INSERT IGNORE INTO genres (name) VALUES ('PPKn');
INSERT IGNORE INTO genres (name) VALUES ('Pendidikan Agama Islam');
INSERT IGNORE INTO genres (name) VALUES ('Seni Budaya');
INSERT IGNORE INTO genres (name) VALUES ('Dongeng');
INSERT IGNORE INTO genres (name) VALUES ('Cerita Rakyat');
INSERT IGNORE INTO genres (name) VALUES ('Ensiklopedia');
INSERT IGNORE INTO genres (name) VALUES ('Komik Edukasi');